cacheFolder: ./.yarn/cache

checksumBehavior: update

cloneConcurrency: 1

enableScripts: true

networkConcurrency: 1

nmHoistingLimits: workspaces

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.5.0.cjs
