#!/usr/bin/env bash

# make cygwin bin as priority
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:$PATH";

(set -o igncr) 2>/dev/null && set -o igncr; # cygwin encoding fix

# absolute path working directory
basecwd=${PWD}
# base script directory
basedir=`dirname "$0"`
# absolute path script directory
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

case `uname` in
  *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

NODE_EXE="$basedir/node.exe"
if ! [ -x "$NODE_EXE" ]; then
  NODE_EXE="$basedir/node"
fi
## find using whereis
if ! [ -x "$NODE_EXE" ]; then
  find_node=($(whereis -b node))
  for i in ${find_node[@]}; do
      if [ -f "$i" ]; then
        NODE_EXE="$i"
      fi
  done
fi
## fallback node
if ! [ -x "$NODE_EXE" ]; then
  NODE_EXE=node
fi

# these paths are passed to node.exe, so they need to match whatever
# kind of paths Node.js thinks it's using, typically win32 paths.
CLI_BASEDIR="$("$NODE_EXE" -p 'require("path").dirname(process.execPath)')"

printf "%s \t %s\n" "node exe" "$NODE_EXE"
printf "%s \t %s\n" "node directory" "$CLI_BASEDIR"

if [ $? -ne 0 ]; then
  # if this didn't work, then everything else below will fail
  echo "Could not determine Node.js install directory" >&2
  exit 1
fi
NPM_CLI_JS="$CLI_BASEDIR/node_modules/npm/bin/npm-cli.js"
NPX_CLI_JS="$CLI_BASEDIR/node_modules/npm/bin/npx-cli.js"
NPM_PREFIX=`"$NODE_EXE" "$NPM_CLI_JS" prefix -g`
NPM_PREFIX_NPX_CLI_JS="$NPM_PREFIX/node_modules/npm/bin/npx-cli.js"

# a path that will fail -f test on any posix bash
NPX_WSL_PATH="/.."

# WSL can run Windows binaries, so we have to give it the win32 path
# however, WSL bash tests against posix paths, so we need to construct that
# to know if npm is installed globally.
if [ `uname` = 'Linux' ] && type wslpath &>/dev/null ; then
  NPX_WSL_PATH=`wslpath "$NPM_PREFIX_NPX_CLI_JS"`
fi
if [ -f "$NPM_PREFIX_NPX_CLI_JS" ] || [ -f "$NPX_WSL_PATH" ]; then
  NPX_CLI_JS="$NPM_PREFIX_NPX_CLI_JS"
fi

#if [ -x "$NODE_EXE" ]; then
  #exec "$NODE_EXE"  "$CLI_BASEDIR/node_modules/corepack/dist/yarn.js" "$@"
#else
  #exec node  "$CLI_BASEDIR/node_modules/corepack/dist/yarn.js" "$@"
#fi

yarn=$("$NODE_EXE" "$CLI_BASEDIR/node_modules/corepack/dist/yarn.js")

echo "cleaning..."
exec "$yarn" workspace warehouse exec "rm -rf dist"
exec "$yarn" workspace hexo-front-matter exec "rm -rf dist"
exec "$yarn" workspace hexo exec "rm -rf dist"
exec "$yarn" workspace hexo-asset-link exec "rm -rf dist"

echo "building..."
exec "$yarn" workspace warehouse run build
exec "$yarn" workspace hexo-front-matter run build
exec "$yarn" workspace hexo run build
exec "$yarn" workspace hexo-asset-link run build

yarn workspaces foreach run build