name: Workspace Tester

on:
  push:
    branches: ['monorepo-v7']
    paths-ignore:
      - '**/*.tgz'
      - '**/*.gz'
      - '**/release*/**'
      - '**garbage-collector**'
      - '**codeql**'
      - '**/workspace-build-release.yml'
  pull_request:
    branches: ['monorepo-v7']
    types:
      - closed
    paths-ignore:
      - '**/release*/**'
      - '**/*.tgz'
      - '**/*.gz'
      - '**/test*/**'
  workflow_dispatch:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: 'ubuntu-latest'
        description: 'Operation system to be used'
      node-version:
        required: false
        type: string
        description: 'Node version to be used'
        default: '14.x'
    secrets:
      ACCESS_TOKEN:
        required: true

permissions: write-all

jobs:
  build:
    uses: ./.github/workflows/workspace-builder.yml
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  tester:
    needs: build
    runs-on: ubuntu-latest
    # set timeout - see https://stackoverflow.com/a/59076067/6404439
    timeout-minutes: 120
    strategy:
      fail-fast: true
      #max-parallel: 3
    env:
      NODE_OPTIONS: '--max_old_space_size=8192' #8192 4096 --expose-gc
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Let's get all the branches
          submodules: recursive
          token: '${{ secrets.ACCESS_TOKEN }}'
          ref: 'monorepo-v7'
      - name: update submodules
        run: |
          echo "init submodules"
          git submodule init
          git submodule foreach "git submodule init"
          echo "sync submodules"
          git submodule sync
          git submodule foreach "git submodule sync"
          echo "update submodules"
          mkdir -p bin >/dev/null 2>&1
          curl -L https://github.com/dimaslanjaka/bin/raw/master/bin/submodule-install > bin/submodule-install
          rm -rf .git/modules
          bash ./bin/submodule-install
        shell: bash
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: Enable corepack
        shell: bash
        run: corepack enable
      - uses: pat-s/always-upload-cache@v3.0.11
        id: cache
        with:
          path: |
            **/.yarn
            ./release*
            ./yarn.lock
            **/dist
          key: ${{ runner.os }}-${{ inputs.node-version }}
          restore-keys: |
            ${{ runner.os }}-${{ inputs.node-version }}
            ${{ runner.os }}-
      - name: Download build-output artifact
        uses: actions/download-artifact@master
        with:
          name: build-output
      - run: yarn install
      - run: npm test
