name: Workspace Tester

on:
  push:
    branches: ['monorepo-v7']
    paths-ignore:
      - '**/*.tgz'
      - '**/*.gz'
      - '**/release*/**'
      - '**garbage-collector**'
      - '**codeql**'
  pull_request:
    branches: ['monorepo-v7']
    types:
      - closed
    paths-ignore:
      - '**/release*/**'
      - '**/*.tgz'
      - '**/*.gz'
      - '**/test*/**'
  workflow_dispatch:
  workflow_call:

permissions: write-all

jobs:
  build:
    uses: ./.github/workflows/workspace-builder.yml
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  tester:
    runs-on: ${{ matrix.os }}
    # set timeout - see https://stackoverflow.com/a/59076067/6404439
    timeout-minutes: 120
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: ['14.x', '16.x', '18.x']
      fail-fast: true
      #max-parallel: 3
    env:
      NODE_OPTIONS: '--max_old_space_size=8192' #8192 4096 --expose-gc
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - run: npm test
